# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan Hu
email: lakehy@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Some blablas and notes.
host: xen
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lakehy.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lakehy

# Build settings
markdown: kramdown
exclude: [books]
keep_files: [devtips, embedman]
